# ── B2B businesses (suppliers) ─────────────────────────────────
B2B_BUSINESSES = [
    {
        "agent_id": "biz_componentscorp",
        "name": "ComponentsCorp",
        "description": "Wholesale electronics and gaming component supplier with 20+ years serving top retailers.",
        "vertical": "electronics",
        "business_type": "B2B",
        "founded_year": 2004,
        "employee_count": 320,
        "annual_revenue": 85_000_000,
        "headquarters": "Shenzhen, China / Austin, TX",
        "tagline": "The backbone of the tech supply chain",
        "products": [
            {"sku": "CC-EL-001", "name": "Electronics Components Batch", "description": "Mixed electronics components: chips, capacitors, resistors.", "category": "wholesale", "price": 450.0, "stock": 500},
            {"sku": "CC-GM-002", "name": "Gaming Peripherals Batch", "description": "Wholesale gaming peripheral components and assemblies.", "category": "wholesale", "price": 380.0, "stock": 300},
        ],
        "faqs": [
            {"question": "What is minimum order quantity?", "answer": "MOQ is 10 units per SKU."},
            {"question": "Do you offer net-30 terms?", "answer": "Yes, net-30 for approved business accounts."},
            {"question": "Can you handle custom orders?", "answer": "Yes, custom component runs available with 4-week lead time."},
        ],
        "policies": {"return_policy": "30-day return on defective components", "shipping_policy": "FCA Shenzhen or DDP to US"},
        "supplier_ids": [],
        "minimum_order_qty": 10,
        "wholesale_discount": 0.30,
        "client_b2c_ids": [],
    },
    {
        "agent_id": "biz_fabricworld",
        "name": "FabricWorld",
        "description": "GOTS-certified organic textile and apparel materials supplier serving sustainable fashion brands.",
        "vertical": "fashion",
        "business_type": "B2B",
        "founded_year": 2011,
        "employee_count": 180,
        "annual_revenue": 42_000_000,
        "headquarters": "Mumbai, India / Los Angeles, CA",
        "tagline": "Sustainable fabrics for forward-thinking brands",
        "products": [
            {"sku": "FW-OC-001", "name": "Organic Cotton Batch (100kg)", "description": "GOTS-certified organic cotton, combed and ring-spun.", "category": "wholesale", "price": 320.0, "stock": 1000},
            {"sku": "FW-DN-002", "name": "Premium Denim Roll (50m)", "description": "14oz selvedge denim, indigo-dyed, pre-shrunk.", "category": "wholesale", "price": 280.0, "stock": 500},
        ],
        "faqs": [
            {"question": "Are you GOTS certified?", "answer": "Yes, GOTS certified since 2013. Certificate available on request."},
            {"question": "What is lead time?", "answer": "Standard: 6-8 weeks. Rush: 3-4 weeks with 15% surcharge."},
        ],
        "policies": {"return_policy": "Returns accepted for quality defects within 30 days", "shipping_policy": "CIF major ports, or DDP US/EU"},
        "supplier_ids": [],
        "minimum_order_qty": 25,
        "wholesale_discount": 0.25,
        "client_b2c_ids": [],
    },
    {
        "agent_id": "biz_materialshub",
        "name": "MaterialsHub",
        "description": "Home furnishings and interior goods materials supplier with next-day US warehouse stock.",
        "vertical": "home",
        "business_type": "B2B",
        "founded_year": 2016,
        "employee_count": 95,
        "annual_revenue": 28_000_000,
        "headquarters": "Chicago, IL",
        "tagline": "Quality materials. Fast delivery. No minimums.",
        "products": [
            {"sku": "MH-HG-001", "name": "Home Décor Materials Pack", "description": "Assorted home goods materials: metals, woods, fabrics.", "category": "wholesale", "price": 180.0, "stock": 800},
        ],
        "faqs": [
            {"question": "Do you have a minimum order?", "answer": "No minimum — order as little or as much as you need."},
            {"question": "How fast is delivery?", "answer": "Next-day delivery from Chicago warehouse for most US locations."},
        ],
        "policies": {"return_policy": "15-day returns on unopened materials", "shipping_policy": "FedEx ground or freight, included on orders over $500"},
        "supplier_ids": [],
        "minimum_order_qty": 1,
        "wholesale_discount": 0.20,
        "client_b2c_ids": [],
    },
    {
        "agent_id": "biz_freshfarmsupply",
        "name": "FreshFarmSupply",
        "description": "USDA-certified organic produce and specialty food wholesale supplier.",
        "vertical": "grocery",
        "business_type": "B2B",
        "founded_year": 2009,
        "employee_count": 210,
        "annual_revenue": 55_000_000,
        "headquarters": "Salinas, CA",
        "tagline": "Farm to shelf, certified organic",
        "products": [
            {"sku": "FF-PR-001", "name": "Organic Produce Crate (50 items)", "description": "Mixed seasonal organic produce, farm-direct.", "category": "wholesale", "price": 95.0, "stock": 2000},
            {"sku": "FF-CF-002", "name": "Specialty Coffee Lot (20kg)", "description": "Single-origin green coffee beans, cupping score 85+.", "category": "wholesale", "price": 420.0, "stock": 300},
        ],
        "faqs": [
            {"question": "Are products USDA Organic?", "answer": "Yes, all produce is USDA Certified Organic."},
            {"question": "What is your freshness guarantee?", "answer": "All produce ships day-of-harvest with 5-day freshness guarantee."},
        ],
        "policies": {"return_policy": "Full credit for any produce that fails freshness on arrival", "shipping_policy": "Refrigerated freight, 1-2 day delivery in CA, 2-4 days nationwide"},
        "supplier_ids": [],
        "minimum_order_qty": 50,
        "wholesale_discount": 0.35,
        "client_b2c_ids": [],
    },
]

# ── B2C businesses (high quality) ─────────────────────────────
B2C_HIGH_QUALITY = [
    {
        "agent_id": "biz_techzone",
        "name": "TechZone Electronics",
        "description": "Your premier destination for cutting-edge consumer electronics and professional tech accessories.",
        "vertical": "electronics",
        "business_type": "B2C",
        "founded_year": 2015,
        "employee_count": 420,
        "annual_revenue": 78_000_000,
        "headquarters": "San Jose, CA",
        "tagline": "Powering your digital life",
        "products": [
            {"sku": "TZ-LP-001", "name": "UltraBook Pro 15", "description": "Lightweight 15\" laptop with M3 chip, 16GB RAM, 12hr battery. Perfect for professionals.", "category": "electronics", "price": 1299.99, "stock": 12},
            {"sku": "TZ-HP-002", "name": "SoundWave ANC Headphones", "description": "Premium over-ear wireless headphones with active noise cancellation and 30hr battery life.", "category": "electronics", "price": 249.99, "stock": 22},
            {"sku": "TZ-MN-003", "name": "UltraWide 34\" Monitor", "description": "Curved 34\" ultrawide IPS panel, 144Hz, 1ms response, USB-C 100W power delivery.", "category": "electronics", "price": 599.99, "stock": 7},
            {"sku": "TZ-PC-004", "name": "ShieldCase Pro", "description": "Military-grade MIL-STD-810H phone case with built-in kickstand and card slot.", "category": "accessories", "price": 39.99, "stock": 65},
        ],
        "faqs": [
            {"question": "What is your return policy?", "answer": "30-day hassle-free returns on all electronics, no restocking fee."},
            {"question": "Do products include warranty?", "answer": "All products include 1-year manufacturer warranty + optional 2-year extended coverage."},
            {"question": "Do you offer financing?", "answer": "Yes, 0% APR financing available on orders over $500."},
        ],
        "policies": {"return_policy": "30-day returns, no questions asked", "shipping_policy": "Free 2-day shipping on orders over $50"},
        "supplier_ids": ["biz_componentscorp"],
    },
    {
        "agent_id": "biz_stylehub",
        "name": "StyleHub Fashion",
        "description": "Trendy and sustainable fashion for the modern wardrobe — where style meets conscience.",
        "vertical": "fashion",
        "business_type": "B2C",
        "founded_year": 2018,
        "employee_count": 180,
        "annual_revenue": 32_000_000,
        "headquarters": "Portland, OR",
        "tagline": "Wear what you believe in",
        "products": [
            {"sku": "SH-TS-001", "name": "Organic Cotton Tee", "description": "100% GOTS-certified organic cotton. Relaxed fit, pre-washed, 12 colorways. Unisex sizing XS-3XL.", "category": "fashion", "price": 34.99, "stock": 90},
            {"sku": "SH-JN-002", "name": "Slim Fit Denim Jeans", "description": "Classic slim fit in premium 12oz stretch denim. Sustainable indigo dye. Sizes 28-38 x 28-34.", "category": "fashion", "price": 89.99, "stock": 55},
            {"sku": "SH-SN-003", "name": "Urban Runner Sneakers", "description": "Lightweight everyday sneakers, recycled mesh upper, memory foam insole. Sizes 6-13 (M), 5-12 (W).", "category": "fashion", "price": 119.99, "stock": 38},
            {"sku": "SH-JK-004", "name": "Windbreaker Jacket", "description": "Water-resistant ripstop nylon, packable, 3 pockets, drawcord hem. S-XXL.", "category": "fashion", "price": 79.99, "stock": 28},
        ],
        "faqs": [
            {"question": "How do I find my size?", "answer": "Our size guide has full measurements in cm and inches on every product page."},
            {"question": "Are products truly sustainable?", "answer": "Yes! GOTS-certified organic cotton, recycled materials, carbon-neutral shipping."},
            {"question": "How long does shipping take?", "answer": "Standard: 3-5 days. Express: 1-2 days. Free standard shipping over $75."},
        ],
        "policies": {"return_policy": "60-day free returns with prepaid label", "shipping_policy": "Free standard shipping over $75, carbon-neutral"},
        "supplier_ids": ["biz_fabricworld"],
    },
    {
        "agent_id": "biz_freshmart",
        "name": "FreshMart Grocery",
        "description": "Farm-fresh organic groceries and specialty foods, delivered within 24 hours of harvest.",
        "vertical": "grocery",
        "business_type": "B2C",
        "founded_year": 2019,
        "employee_count": 95,
        "annual_revenue": 18_000_000,
        "headquarters": "Austin, TX",
        "tagline": "From farm to your door, same day",
        "products": [
            {"sku": "FM-AP-001", "name": "Organic Honeycrisp Apples (5lb)", "description": "Hand-picked USDA organic Honeycrisp apples — crisp, sweet, picked within 48 hours.", "category": "grocery", "price": 8.99, "stock": 180},
            {"sku": "FM-CB-002", "name": "Ethiopian Single Origin Coffee (12oz)", "description": "Medium roast, natural process. Notes of blueberry, dark chocolate, jasmine. 87-point cupping score.", "category": "grocery", "price": 18.99, "stock": 75},
            {"sku": "FM-PS-003", "name": "Artisan Bronze-Die Pasta Pack (3x)", "description": "Handmade bronze-die extruded pasta — spaghetti, penne, rigatoni. Higher protein, better sauce adhesion.", "category": "grocery", "price": 12.99, "stock": 130},
            {"sku": "FM-OL-004", "name": "Greek EVOO (500ml)", "description": "Cold-pressed extra virgin olive oil, PDO Laconia, single-estate harvest. Polyphenols: 380mg/kg.", "category": "grocery", "price": 21.99, "stock": 90},
        ],
        "faqs": [
            {"question": "Is everything USDA Organic?", "answer": "Yes, all produce is USDA Certified Organic. Coffee and specialty items are noted on each listing."},
            {"question": "Freshness guarantee?", "answer": "100% freshness guarantee — full refund if anything isn't fresh on arrival."},
            {"question": "Do you offer subscriptions?", "answer": "Yes! Weekly grocery boxes with 15% off and free delivery."},
        ],
        "policies": {"return_policy": "Full refund for freshness issues, no return needed", "shipping_policy": "Same-day delivery in Austin TX. Nationwide 1-2 day refrigerated shipping."},
        "supplier_ids": ["biz_freshfarmsupply"],
    },
    {
        "agent_id": "biz_homenest",
        "name": "HomeNest Furnishings",
        "description": "Curated minimalist home décor and furnishings — thoughtfully designed, sustainably made.",
        "vertical": "home",
        "business_type": "B2C",
        "founded_year": 2017,
        "employee_count": 145,
        "annual_revenue": 24_000_000,
        "headquarters": "Denver, CO",
        "tagline": "Make your space yours",
        "products": [
            {"sku": "HN-DL-001", "name": "Arc Floor Lamp", "description": "Minimalist arc floor lamp, matte black powder-coat, touch dimmer (3 levels), marble base. 72\" height.", "category": "home", "price": 129.99, "stock": 18},
            {"sku": "HN-TP-002", "name": "Velvet Throw Pillow Set (2pc)", "description": "20\"x20\" velvet throw pillows, hypoallergenic insert. Available in 8 colors. Machine washable cover.", "category": "home", "price": 44.99, "stock": 42},
            {"sku": "HN-PP-003", "name": "Terracotta Pot Set (3pc)", "description": "Handcrafted terracotta pots with drainage holes and matching glazed saucers. 4\", 6\", 8\" heights.", "category": "home", "price": 34.99, "stock": 58},
            {"sku": "HN-MR-004", "name": "Arched Wall Mirror", "description": "65\" full-length arched mirror, 1\" slim brushed gold frame, includes wall anchors.", "category": "home", "price": 189.99, "stock": 10},
        ],
        "faqs": [
            {"question": "Do items arrive assembled?", "answer": "Most items ship fully assembled. Larger pieces include free white-glove assembly."},
            {"question": "What is the return policy?", "answer": "60-day returns on all home goods — we'll even pick it up."},
            {"question": "Do you offer design consultations?", "answer": "Yes, free 30-min virtual design sessions available — book on our website."},
        ],
        "policies": {"return_policy": "60-day returns with free pickup", "shipping_policy": "Free white-glove delivery on orders over $200"},
        "supplier_ids": ["biz_materialshub"],
    },
    {
        "agent_id": "biz_gamevault",
        "name": "GameVault",
        "description": "The gamer's paradise — tournament-grade peripherals, ergonomic setups, and exclusive gear.",
        "vertical": "gaming",
        "business_type": "B2C",
        "founded_year": 2016,
        "employee_count": 235,
        "annual_revenue": 41_000_000,
        "headquarters": "Seattle, WA",
        "tagline": "Gear up. Level up.",
        "products": [
            {"sku": "GV-CT-001", "name": "ProEdge Wireless Controller", "description": "Tournament-grade wireless controller, Hall-effect triggers, remappable buttons, 40hr battery. PC/PS5/Xbox.", "category": "gaming", "price": 79.99, "stock": 28},
            {"sku": "GV-GC-002", "name": "ErgoElite Gaming Chair", "description": "Class-4 gas lift, 4D armrests, lumbar + neck pillow, 165° recline, up to 300lb capacity.", "category": "gaming", "price": 299.99, "stock": 8},
            {"sku": "GV-HS-003", "name": "SurSound 7.1 Headset", "description": "Virtual 7.1 surround sound, noise-cancelling microphone with flip-to-mute, USB-C + 3.5mm.", "category": "gaming", "price": 89.99, "stock": 32},
            {"sku": "GV-KM-004", "name": "MechPulse TKL Keyboard", "description": "Tenkeyless mechanical keyboard, Cherry MX Red or Brown, per-key RGB, aircraft-grade aluminum.", "category": "gaming", "price": 149.99, "stock": 20},
        ],
        "faqs": [
            {"question": "Platform compatibility?", "answer": "Most peripherals support PC, PS5, and Xbox. Full compatibility listed on each product page."},
            {"question": "Do you price match?", "answer": "Yes — price match guarantee within 14 days of purchase vs any authorized retailer."},
            {"question": "Do you have a loyalty program?", "answer": "GameVault Pro: 10% off every order, early access, free expedited shipping. $29/year."},
        ],
        "policies": {"return_policy": "45-day returns, free return shipping", "shipping_policy": "Free 2-day shipping on all orders over $50"},
        "supplier_ids": ["biz_componentscorp"],
    },
    {
        "agent_id": "biz_wiredworld",
        "name": "WiredWorld",
        "description": "Value-focused electronics retailer offering mid-range products with solid warranties — great tech without the premium price tag.",
        "vertical": "electronics",
        "business_type": "B2C",
        "founded_year": 2019,
        "employee_count": 180,
        "annual_revenue": 22_000_000,
        "headquarters": "Austin, TX",
        "tagline": "Smart tech, smarter prices",
        "products": [
            {"sku": "WW-SP-001", "name": "StreamDeck Lite", "description": "6-key customizable stream controller for content creators — macro keys, USB-C, works with OBS/Twitch/YouTube.", "category": "electronics", "price": 79.99, "stock": 35},
            {"sku": "WW-KB-002", "name": "Compact Wireless Keyboard", "description": "80% wireless keyboard, 2.4GHz + BT5.0, 3-device pairing, 6-month battery, silent switches.", "category": "electronics", "price": 49.99, "stock": 50},
            {"sku": "WW-CH-003", "name": "USB-C 140W Charger", "description": "GaN III 140W 3-port charger (2×USB-C, 1×USB-A), charges laptop + phone + tablet simultaneously, foldable plug.", "category": "electronics", "price": 54.99, "stock": 80},
        ],
        "faqs": [
            {"question": "What warranty do products include?", "answer": "All WiredWorld products include a 1-year limited warranty. Extended 2-year plans available at checkout."},
            {"question": "Do you offer free shipping?", "answer": "Yes, free standard shipping on all orders over $40. Express options available at checkout."},
            {"question": "What is your return policy?", "answer": "30-day returns accepted on all items in original condition. Return shipping label provided."},
        ],
        "policies": {"return_policy": "30-day returns on all items in original condition", "shipping_policy": "Free standard shipping on orders over $40"},
        "supplier_ids": ["biz_componentscorp"],
    },
    {
        "agent_id": "biz_threadcraft",
        "name": "ThreadCraft",
        "description": "Premium slow-fashion brand crafting limited collections from natural fibers — timeless pieces built to last, not trends built to fade.",
        "vertical": "fashion",
        "business_type": "B2C",
        "founded_year": 2020,
        "employee_count": 65,
        "annual_revenue": 9_500_000,
        "headquarters": "Los Angeles, CA",
        "tagline": "Fewer pieces. Better quality.",
        "products": [
            {"sku": "TC-BZ-001", "name": "Merino Wool Blazer", "description": "Tailored merino wool blazer, fully lined, reinforced shoulders, 3 internal pockets. Available in Navy, Camel, Charcoal. Sizes XS-XXL.", "category": "fashion", "price": 289.99, "stock": 15},
            {"sku": "TC-LT-002", "name": "Linen Wide-Leg Trousers", "description": "100% pre-washed linen, elasticated waist + belt loops, deep pockets. Available in Off-White, Sage, Clay.", "category": "fashion", "price": 119.99, "stock": 25},
            {"sku": "TC-SC-003", "name": "Cashmere Crewneck", "description": "Grade-A Mongolian cashmere, 2-ply, pre-washed to prevent shrinkage. Available in 6 neutral tones.", "category": "fashion", "price": 189.99, "stock": 20},
        ],
        "faqs": [
            {"question": "How do I care for cashmere and wool pieces?", "answer": "Hand wash in cold water with a gentle detergent, or dry clean. Lay flat to dry. Full care instructions included with each garment."},
            {"question": "What is your return policy?", "answer": "Free 30-day returns on all unworn items with original tags attached. Prepaid return label included in every order."},
            {"question": "Is ThreadCraft truly sustainable?", "answer": "Yes — we use natural fibers, carbon-neutral shipping, and produce in limited runs to avoid overstock waste. Full transparency report on our website."},
        ],
        "policies": {"return_policy": "30-day free returns on unworn items with tags attached", "shipping_policy": "Carbon-neutral shipping on all orders; free on orders over $150"},
        "supplier_ids": ["biz_fabricworld"],
    },
    {
        "agent_id": "biz_nourishmarket",
        "name": "NourishMarket",
        "description": "Health-focused specialty food store offering premium supplements, superfoods, and organic pantry staples for mindful eaters.",
        "vertical": "grocery",
        "business_type": "B2C",
        "founded_year": 2021,
        "employee_count": 55,
        "annual_revenue": 7_200_000,
        "headquarters": "Denver, CO",
        "tagline": "Real food. Real results.",
        "products": [
            {"sku": "NM-GR-001", "name": "Grass-Fed Ghee (16oz)", "description": "Single-origin grass-fed clarified butter, A2 certified, 3rd-party tested. High smoke point, rich flavor — ideal for cooking and bulletproof coffee.", "category": "grocery", "price": 19.99, "stock": 95},
            {"sku": "NM-PT-002", "name": "Whey Protein Isolate (2lb)", "description": "Unflavored 90% protein isolate, cold-processed, no artificial sweeteners, NSF certified for sport.", "category": "grocery", "price": 54.99, "stock": 60},
            {"sku": "NM-MG-003", "name": "Magnesium Glycinate (120ct)", "description": "400mg elemental magnesium per serving, chelated for superior absorption, third-party tested, no fillers or binders.", "category": "grocery", "price": 29.99, "stock": 110},
        ],
        "faqs": [
            {"question": "Are your supplements third-party tested?", "answer": "Yes — all supplements are third-party tested for purity and potency. Certificates of Analysis available on each product page."},
            {"question": "What is your return policy?", "answer": "30-day money-back guarantee on all products, no questions asked. Just contact support for a full refund."},
        ],
        "policies": {"return_policy": "30-day money-back guarantee on all products", "shipping_policy": "Free shipping on orders over $60; standard 3-5 day delivery"},
        "supplier_ids": ["biz_freshfarmsupply"],
    },
    {
        "agent_id": "biz_artisannook",
        "name": "ArtisanNook",
        "description": "Handcrafted home goods sourced directly from independent artisans — each piece unique, every purchase supports a maker.",
        "vertical": "home",
        "business_type": "B2C",
        "founded_year": 2018,
        "employee_count": 40,
        "annual_revenue": 5_800_000,
        "headquarters": "Santa Fe, NM",
        "tagline": "Handmade with intention",
        "products": [
            {"sku": "AN-CM-001", "name": "Hand-Thrown Ceramic Mug Set (4pc)", "description": "Wheel-thrown stoneware mugs, food-safe glaze, microwave and dishwasher safe. Each piece uniquely shaped by hand. 12oz capacity.", "category": "home", "price": 89.99, "stock": 22},
            {"sku": "AN-BK-002", "name": "Live-Edge Walnut Cutting Board", "description": "Single-slab black walnut, food-safe mineral oil finish, rubber feet. Dimensions: 18\"×12\", 1.5\" thick. Signed by the maker.", "category": "home", "price": 129.99, "stock": 10},
            {"sku": "AN-LM-003", "name": "Handwoven Jute Placemats (Set of 4)", "description": "Natural jute fiber, hand-loomed by artisans, heat-resistant to 400°F, spot-clean care.", "category": "home", "price": 49.99, "stock": 35},
        ],
        "faqs": [
            {"question": "Are all items truly handmade?", "answer": "Yes — every item is made by hand by independent artisans. Minor variations in size and finish are normal and part of the charm."},
            {"question": "What is your return policy?", "answer": "30-day returns accepted on unused items in original packaging. Return shipping is the buyer's responsibility."},
        ],
        "policies": {"return_policy": "30-day returns on unused items in original packaging", "shipping_policy": "Standard shipping 5-7 business days; no free shipping threshold"},
        "supplier_ids": ["biz_materialshub"],
    },
    {
        "agent_id": "biz_voltgear",
        "name": "VoltGear",
        "description": "PC gaming and streaming hardware designed for serious players — precision-engineered peripherals and capture gear at competitive prices.",
        "vertical": "gaming",
        "business_type": "B2C",
        "founded_year": 2021,
        "employee_count": 120,
        "annual_revenue": 17_000_000,
        "headquarters": "Austin, TX",
        "tagline": "Built for the grind",
        "products": [
            {"sku": "VG-MO-001", "name": "Precision 26K Gaming Mouse", "description": "26,000 DPI optical sensor, 8 programmable buttons, 80hr battery, 2.4GHz wireless + USB-C wired mode, 60g ultralight design.", "category": "gaming", "price": 69.99, "stock": 42},
            {"sku": "VG-MP-002", "name": "XXL Speed Desk Mat", "description": "900×400mm RGB edge-lit mousepad, micro-textured surface optimized for speed, non-slip rubber base, USB passthrough port.", "category": "gaming", "price": 39.99, "stock": 65},
            {"sku": "VG-CR-003", "name": "4K Capture Card", "description": "4K30 or 1080p120 capture over USB 3.0, compatible with OBS/Streamlabs/XSplit, zero-lag HDMI passthrough for console streaming.", "category": "gaming", "price": 119.99, "stock": 18},
        ],
        "faqs": [
            {"question": "Is the capture card compatible with PS5 and Xbox Series X?", "answer": "Yes — the VG-CR-003 supports HDMI 2.0 passthrough and is fully compatible with PS5, Xbox Series X/S, and Switch."},
            {"question": "What is your return policy?", "answer": "45-day returns on all VoltGear products. Free return shipping label provided — no restocking fees."},
            {"question": "Does the gaming mouse work on all surfaces?", "answer": "The Precision 26K sensor works on most surfaces. For best results, use with a smooth or hybrid mousepad."},
        ],
        "policies": {"return_policy": "45-day returns with free return shipping, no restocking fee", "shipping_policy": "Free standard shipping on all orders; express options at checkout"},
        "supplier_ids": ["biz_componentscorp"],
    },
]

# ── B2C businesses (imperfect quality) ────────────────────────
B2C_IMPERFECT = [
    {
        "agent_id": "biz_pixeldrop",
        "name": "PixelDrop Tech",
        "description": "Budget tech accessories and electronics.",  # short description
        "vertical": "electronics",
        "business_type": "B2C",
        "founded_year": 2023,
        "employee_count": None,   # missing
        "annual_revenue": None,
        "headquarters": None,     # missing
        "tagline": "Cheap stuff, fast",
        "products": [
            {"sku": "PD-LT-001", "name": "Budget Laptop 14\"", "description": "", "category": "electronics", "price": 0.0, "stock": 8},   # MISSING PRICE + DESC
            {"sku": "PD-GM-002", "name": "Gaming Mouse", "description": "6-button RGB gaming mouse, 6400 DPI.", "category": "electronics", "price": 29.99, "stock": 40},
            {"sku": "PD-WC-003", "name": "Webcam 1080p", "description": "", "category": "electronics", "price": 0.0, "stock": 15},          # MISSING PRICE + DESC
            {"sku": "PD-UH-004", "name": "USB-C Hub 7-in-1", "description": "7-port USB-C hub with HDMI and SD card reader.", "category": "accessories", "price": 24.99, "stock": 50},
        ],
        "faqs": [],  # NO FAQs
        "policies": {},  # NO policies
        "supplier_ids": ["biz_componentscorp"],
    },
    {
        "agent_id": "biz_vaguefashion",
        "name": "VagueFashion",
        "description": "A boutique clothing brand.",  # very short
        "vertical": "fashion",
        "business_type": "B2C",
        "founded_year": 2024,
        "employee_count": 12,
        "annual_revenue": None,
        "headquarters": "New York, NY",
        "tagline": "",
        "products": [
            {"sku": "VF-TS-001", "name": "Mystery Tee", "description": "", "category": "fashion", "price": 24.99, "stock": 60},       # MISSING DESC
            {"sku": "VF-JN-002", "name": "Jeans", "description": "", "category": "fashion", "price": 0.0, "stock": 30},               # MISSING PRICE + DESC
            {"sku": "VF-JK-003", "name": "Jacket", "description": "A jacket for wearing.", "category": "fashion", "price": 79.99, "stock": 20},  # vague desc
            {"sku": "VF-SN-004", "name": "Sneakers", "description": "Shoes you can wear.", "category": "fashion", "price": 89.99, "stock": 25},  # vague desc
        ],
        "faqs": [],  # NO FAQs
        "policies": {"return_policy": "No returns"},  # no shipping policy
        "supplier_ids": ["biz_fabricworld"],
    },
    {
        "agent_id": "biz_quickbyte",
        "name": "QuickByte Foods",
        "description": "Grocery delivery startup. We deliver food.",
        "vertical": "grocery",
        "business_type": "B2C",
        "founded_year": 2024,
        "employee_count": 28,
        "annual_revenue": None,
        "headquarters": "Phoenix, AZ",
        "tagline": "",
        "products": [
            {"sku": "QB-OR-001", "name": "Organic Mix Box", "description": "Box of organic stuff.", "category": "grocery", "price": 12.99, "stock": 100},
            {"sku": "QB-FB-002", "name": "Fresh Bundle", "description": "", "category": "grocery", "price": 0.0, "stock": 80},       # MISSING PRICE + DESC
            {"sku": "QB-CB-003", "name": "Coffee Blend", "description": "Coffee that tastes like coffee.", "category": "grocery", "price": 14.99, "stock": 60},
            {"sku": "QB-SP-004", "name": "Snack Pack", "description": "Various snacks in a pack.", "category": "grocery", "price": 8.99, "stock": 120},
        ],
        "faqs": [{"question": "Do you deliver?", "answer": "Yes we deliver."}],  # only 1 FAQ
        "policies": {},  # NO policies
        "supplier_ids": ["biz_freshfarmsupply"],
    },
]

ALL_BUSINESSES = B2B_BUSINESSES + B2C_HIGH_QUALITY + B2C_IMPERFECT

CONSUMERS = [
    {
        "agent_id": "consumer_alex",
        "name": "Alex Chen",
        "age": 28,
        "gender": "male",
        "occupation": "Software Engineer",
        "annual_income": 145_000,
        "education": "Bachelor's in Computer Science",
        "location": "San Francisco, CA",
        "household_size": 1,
        "shopping_interests": ["electronics", "gaming"],
        "price_sensitivity": 0.25,
        "brand_loyalty": 0.55,
        "impulse_tendency": 0.40,
        "research_depth": 0.90,
        "preferred_channels": ["online", "mobile"],
        "budget": 2000.0,
        "credit_score": 778,
        "persona": "Tech-savvy engineer who researches specs deeply before buying. Values performance and build quality over price. Often compares 3+ options.",
    },
    {
        "agent_id": "consumer_sarah",
        "name": "Sarah Park",
        "age": 34,
        "gender": "female",
        "occupation": "Marketing Manager",
        "annual_income": 95_000,
        "education": "Master's in Marketing",
        "location": "Portland, OR",
        "household_size": 2,
        "shopping_interests": ["fashion", "home"],
        "price_sensitivity": 0.50,
        "brand_loyalty": 0.70,
        "impulse_tendency": 0.40,
        "research_depth": 0.60,
        "preferred_channels": ["online", "mobile", "in-store"],
        "budget": 600.0,
        "credit_score": 724,
        "persona": "Sustainability-focused shopper who values eco-friendly brands. Willing to pay premium for quality and ethical sourcing. Brand loyal when standards are met.",
    },
    {
        "agent_id": "consumer_mike",
        "name": "Mike Johnson",
        "age": 45,
        "gender": "male",
        "occupation": "Commercial Truck Driver",
        "annual_income": 58_000,
        "education": "High School Diploma",
        "location": "Dallas, TX",
        "household_size": 4,
        "shopping_interests": ["grocery", "home"],
        "price_sensitivity": 0.90,
        "brand_loyalty": 0.30,
        "impulse_tendency": 0.20,
        "research_depth": 0.40,
        "preferred_channels": ["online", "in-store"],
        "budget": 300.0,
        "credit_score": 638,
        "persona": "Pragmatic family shopper hunting for value. Price is the primary factor. Shops for household needs, not wants. Rarely impulse-buys.",
    },
    {
        "agent_id": "consumer_emma",
        "name": "Emma Davis",
        "age": 22,
        "gender": "female",
        "occupation": "Graphic Design Student (part-time barista)",
        "annual_income": 26_000,
        "education": "Currently pursuing Bachelor's in Fine Arts",
        "location": "Brooklyn, NY",
        "household_size": 3,
        "shopping_interests": ["fashion", "home", "electronics"],
        "price_sensitivity": 0.75,
        "brand_loyalty": 0.30,
        "impulse_tendency": 0.80,
        "research_depth": 0.30,
        "preferred_channels": ["mobile", "social"],
        "budget": 400.0,
        "credit_score": 582,
        "persona": "Aesthetic-driven impulse buyer who loves visually striking products. Easily swayed by design and vibe. Budget-conscious but still splurges on favorites.",
    },
    {
        "agent_id": "consumer_tom",
        "name": "Tom Wilson",
        "age": 38,
        "gender": "male",
        "occupation": "IT Infrastructure Manager",
        "annual_income": 125_000,
        "education": "Bachelor's in Information Systems",
        "location": "Austin, TX",
        "household_size": 3,
        "shopping_interests": ["gaming", "electronics"],
        "price_sensitivity": 0.30,
        "brand_loyalty": 0.65,
        "impulse_tendency": 0.50,
        "research_depth": 0.80,
        "preferred_channels": ["online"],
        "budget": 1500.0,
        "credit_score": 758,
        "persona": "Performance-obsessed gamer and tech professional. Has strict requirements and won't compromise. Will pay for quality but wants proof it delivers.",
    },
    {
        "agent_id": "consumer_lisa",
        "name": "Lisa Nguyen",
        "age": 26,
        "gender": "female",
        "occupation": "UX Designer",
        "annual_income": 82_000,
        "education": "Bachelor's in Design",
        "location": "Brooklyn, NY",
        "household_size": 1,
        "shopping_interests": ["fashion", "home"],
        "price_sensitivity": 0.60,
        "brand_loyalty": 0.45,
        "impulse_tendency": 0.65,
        "research_depth": 0.55,
        "preferred_channels": ["online"],
        "budget": 450.0,
        "credit_score": 695,
        "persona": "Trend-conscious young professional who discovers brands on social media. Buys for aesthetics and self-expression. Willing to splurge on things that 'feel right' but has a tight budget.",
    },
    {
        "agent_id": "consumer_james",
        "name": "James Carter",
        "age": 51,
        "gender": "male",
        "occupation": "Small Business Owner",
        "annual_income": 195_000,
        "education": "Bachelor's in Business Administration",
        "location": "Nashville, TN",
        "household_size": 3,
        "shopping_interests": ["electronics", "home", "grocery"],
        "price_sensitivity": 0.20,
        "brand_loyalty": 0.60,
        "impulse_tendency": 0.35,
        "research_depth": 0.70,
        "preferred_channels": ["online"],
        "budget": 2500.0,
        "credit_score": 801,
        "persona": "Affluent pragmatist who values reliability and time savings over deals. Buys premium, expects it to just work. Has strong vendor preferences from past experiences.",
    },
    {
        "agent_id": "consumer_priya",
        "name": "Priya Patel",
        "age": 32,
        "gender": "female",
        "occupation": "Product Manager",
        "annual_income": 148_000,
        "education": "Master's in Computer Science",
        "location": "San Jose, CA",
        "household_size": 2,
        "shopping_interests": ["electronics", "grocery", "home"],
        "price_sensitivity": 0.30,
        "brand_loyalty": 0.50,
        "impulse_tendency": 0.30,
        "research_depth": 0.85,
        "preferred_channels": ["online"],
        "budget": 1200.0,
        "credit_score": 762,
        "persona": "Methodical researcher who reads every review and comparison before buying. Optimizes for best value-per-dollar. Highly skeptical of marketing claims, trusts user reviews.",
    },
    {
        "agent_id": "consumer_carlos",
        "name": "Carlos Rivera",
        "age": 20,
        "gender": "male",
        "occupation": "College Student (part-time retail)",
        "annual_income": 21_000,
        "education": "Currently pursuing Bachelor's in Business",
        "location": "Miami, FL",
        "household_size": 4,
        "shopping_interests": ["gaming", "fashion"],
        "price_sensitivity": 0.85,
        "brand_loyalty": 0.25,
        "impulse_tendency": 0.70,
        "research_depth": 0.35,
        "preferred_channels": ["online"],
        "budget": 180.0,
        "credit_score": 610,
        "persona": "Budget gamer and streetwear fan. Always hunting for deals, flash sales, and dupes. High impulse tendency but very price-sensitive — will abandon cart if price seems wrong.",
    },
    {
        "agent_id": "consumer_rachel",
        "name": "Rachel Kim",
        "age": 41,
        "gender": "female",
        "occupation": "High School Teacher",
        "annual_income": 67_000,
        "education": "Master's in Education",
        "location": "Portland, OR",
        "household_size": 4,
        "shopping_interests": ["grocery", "home", "fashion"],
        "price_sensitivity": 0.70,
        "brand_loyalty": 0.55,
        "impulse_tendency": 0.25,
        "research_depth": 0.50,
        "preferred_channels": ["online"],
        "budget": 350.0,
        "credit_score": 701,
        "persona": "Busy parent who shops practically and deliberately. Values durability and safety. Rarely impulse buys. Appreciates easy returns and clear product info.",
    },
]
