SUPPLIERS = [
    {
        "agent_id": "supplier_componentscorp",
        "name": "ComponentsCorp",
        "description": "Wholesale electronics and gaming component supplier serving tech retailers.",
        "catalog": [
            {"sku": "CC-BULK-001", "name": "Electronics Components Batch", "category": "wholesale"},
            {"sku": "CC-BULK-002", "name": "Gaming Peripherals Batch", "category": "wholesale"},
        ],
    },
    {
        "agent_id": "supplier_fabricworld",
        "name": "FabricWorld",
        "description": "Sustainable textile and apparel materials for fashion brands.",
        "catalog": [
            {"sku": "FW-BULK-001", "name": "Organic Cotton Batch", "category": "wholesale"},
            {"sku": "FW-BULK-002", "name": "Denim Fabric Roll", "category": "wholesale"},
        ],
    },
    {
        "agent_id": "supplier_materialshub",
        "name": "MaterialsHub",
        "description": "Home furnishings and décor materials for interior goods retailers.",
        "catalog": [
            {"sku": "MH-BULK-001", "name": "Home Décor Materials Batch", "category": "wholesale"},
        ],
    },
]

MERCHANTS = [
    {
        "agent_id": "merchant_techzone",
        "name": "TechZone Electronics",
        "description": "Your premier destination for cutting-edge electronics and tech accessories.",
        "vertical": "electronics",
        "supplier_id": "supplier_componentscorp",
        "products": [
            {
                "sku": "TZ-LP-001",
                "name": "UltraBook Pro 15",
                "description": "Lightweight laptop with M3 chip, 12hr battery, perfect for professionals.",
                "category": "electronics",
                "price": 1299.99,
                "stock": 12,
            },
            {
                "sku": "TZ-HP-002",
                "name": "SoundWave ANC Headphones",
                "description": "Premium noise-cancelling wireless headphones with 30hr battery life.",
                "category": "electronics",
                "price": 249.99,
                "stock": 20,
            },
            {
                "sku": "TZ-MN-004",
                "name": "UltraWide 34\" Monitor",
                "description": "Curved ultrawide monitor, 144Hz, IPS panel, USB-C power delivery.",
                "category": "electronics",
                "price": 599.99,
                "stock": 7,
            },
            {
                "sku": "TZ-PC-003",
                "name": "ShieldCase Pro",
                "description": "Military-grade phone case with built-in kickstand and card slot.",
                "category": "accessories",
                "price": 39.99,
                "stock": 60,
            },
        ],
        "faqs": [
            {"question": "What is your return policy?", "answer": "30-day hassle-free returns on all electronics."},
            {"question": "Do you offer warranty?", "answer": "All products include a 1-year manufacturer warranty."},
            {"question": "Do you offer financing?", "answer": "Yes, 0% APR financing on orders over $500."},
        ],
    },
    {
        "agent_id": "merchant_stylehub",
        "name": "StyleHub Fashion",
        "description": "Trendy and sustainable fashion for the modern wardrobe.",
        "vertical": "fashion",
        "supplier_id": "supplier_fabricworld",
        "products": [
            {
                "sku": "SH-TS-001",
                "name": "Organic Cotton Tee",
                "description": "Soft, sustainably-sourced 100% organic cotton t-shirt. 12 colors.",
                "category": "fashion",
                "price": 34.99,
                "stock": 80,
            },
            {
                "sku": "SH-JN-002",
                "name": "Slim Fit Denim Jeans",
                "description": "Classic slim fit jeans in premium stretch denim. Sizes 28-38.",
                "category": "fashion",
                "price": 89.99,
                "stock": 50,
            },
            {
                "sku": "SH-SN-003",
                "name": "Urban Runner Sneakers",
                "description": "Lightweight everyday sneakers with memory foam insole. Sizes 6-13.",
                "category": "fashion",
                "price": 119.99,
                "stock": 35,
            },
            {
                "sku": "SH-JK-004",
                "name": "Windbreaker Jacket",
                "description": "Water-resistant windbreaker with packable design. S–XXL.",
                "category": "fashion",
                "price": 79.99,
                "stock": 25,
            },
        ],
        "faqs": [
            {"question": "How do I find my size?", "answer": "Check our size guide on each product page — measurements in both cm and inches."},
            {"question": "Are products sustainable?", "answer": "Yes! We use GOTS-certified organic cotton and recycled materials throughout."},
            {"question": "How long does shipping take?", "answer": "Standard: 3-5 business days. Express: 1-2 business days."},
        ],
    },
    {
        "agent_id": "merchant_freshmart",
        "name": "FreshMart Grocery",
        "description": "Farm-fresh groceries and organic produce, delivered fast.",
        "vertical": "grocery",
        "supplier_id": None,
        "products": [
            {
                "sku": "FM-AP-001",
                "name": "Organic Honeycrisp Apples (5lb)",
                "description": "Hand-picked organic apples — crisp, sweet, farm-direct.",
                "category": "grocery",
                "price": 8.99,
                "stock": 150,
            },
            {
                "sku": "FM-CB-002",
                "name": "Single Origin Coffee Beans (12oz)",
                "description": "Ethiopian single-origin medium roast — notes of blueberry and chocolate.",
                "category": "grocery",
                "price": 18.99,
                "stock": 70,
            },
            {
                "sku": "FM-PS-003",
                "name": "Artisan Pasta Pack (3x)",
                "description": "Handmade bronze-die pasta — spaghetti, penne, and rigatoni.",
                "category": "grocery",
                "price": 12.99,
                "stock": 120,
            },
            {
                "sku": "FM-OL-004",
                "name": "Extra Virgin Olive Oil (500ml)",
                "description": "Cold-pressed EVOO from Greek family farms. PDO certified.",
                "category": "grocery",
                "price": 21.99,
                "stock": 80,
            },
        ],
        "faqs": [
            {"question": "Are products certified organic?", "answer": "Most produce is USDA Certified Organic — look for the green badge."},
            {"question": "Freshness guarantee?", "answer": "We guarantee freshness or your money back. Most items last 5-7 days."},
            {"question": "Do you offer subscription?", "answer": "Yes! Subscribe and save 15% on weekly grocery boxes."},
        ],
    },
    {
        "agent_id": "merchant_homenest",
        "name": "HomeNest Furnishings",
        "description": "Stylish, affordable home décor and furnishings for every space.",
        "vertical": "home",
        "supplier_id": "supplier_materialshub",
        "products": [
            {
                "sku": "HN-DL-001",
                "name": "Arc Floor Lamp",
                "description": "Minimalist arc floor lamp with touch dimmer, matte black finish.",
                "category": "home",
                "price": 129.99,
                "stock": 18,
            },
            {
                "sku": "HN-TP-002",
                "name": "Velvet Throw Pillow Set (2x)",
                "description": "Luxurious velvet throw pillows in dusty rose or sage green. 20\"x20\".",
                "category": "home",
                "price": 44.99,
                "stock": 40,
            },
            {
                "sku": "HN-PP-003",
                "name": "Terracotta Plant Pot Set (3x)",
                "description": "Handcrafted terracotta pots with drainage holes and matching saucers.",
                "category": "home",
                "price": 34.99,
                "stock": 55,
            },
            {
                "sku": "HN-MR-004",
                "name": "Arched Wall Mirror",
                "description": "Full-length arched mirror with slim gold frame, 65\" tall.",
                "category": "home",
                "price": 189.99,
                "stock": 10,
            },
        ],
        "faqs": [
            {"question": "Do items ship assembled?", "answer": "Most items ship fully assembled. Large furniture includes free assembly."},
            {"question": "Return policy?", "answer": "60-day returns on all home furnishings, no questions asked."},
            {"question": "Interior design help?", "answer": "Yes! Free 30-minute virtual design consultations available on request."},
        ],
    },
    {
        "agent_id": "merchant_gamevault",
        "name": "GameVault",
        "description": "Everything for gamers — peripherals, gear, and accessories.",
        "vertical": "gaming",
        "supplier_id": "supplier_componentscorp",
        "products": [
            {
                "sku": "GV-CT-001",
                "name": "ProEdge Gaming Controller",
                "description": "Tournament-grade wireless controller with Hall-effect triggers, 40hr battery.",
                "category": "gaming",
                "price": 79.99,
                "stock": 28,
            },
            {
                "sku": "GV-GC-002",
                "name": "ErgoElite Gaming Chair",
                "description": "Ergonomic racing-style chair with 4D armrests and lumbar support.",
                "category": "gaming",
                "price": 299.99,
                "stock": 8,
            },
            {
                "sku": "GV-HS-003",
                "name": "SurSound 7.1 Headset",
                "description": "Virtual 7.1 surround gaming headset with noise-cancelling mic.",
                "category": "gaming",
                "price": 89.99,
                "stock": 30,
            },
            {
                "sku": "GV-KM-004",
                "name": "MechPulse TKL Keyboard",
                "description": "Tenkeyless mechanical keyboard, Cherry MX switches, per-key RGB.",
                "category": "gaming",
                "price": 149.99,
                "stock": 20,
            },
        ],
        "faqs": [
            {"question": "Platform compatibility?", "answer": "Most peripherals work on PC, PS5, and Xbox. Check each product page."},
            {"question": "Do you price match?", "answer": "Yes — price match any authorized retailer within 14 days of purchase."},
            {"question": "Pro program?", "answer": "GameVault Pro members get early access and 10% off every order."},
        ],
    },
]

CONSUMERS = [
    {
        "agent_id": "consumer_alex",
        "name": "Alex Chen",
        "persona": "Tech enthusiast who loves the latest gadgets. Research-oriented, reads specs carefully before buying.",
        "preferences": ["electronics", "gaming"],
        "budget": 2000.0,
    },
    {
        "agent_id": "consumer_sarah",
        "name": "Sarah Park",
        "persona": "Fashion-forward sustainability advocate. Values eco-friendly brands and premium quality.",
        "preferences": ["fashion", "home"],
        "budget": 600.0,
    },
    {
        "agent_id": "consumer_mike",
        "name": "Mike Johnson",
        "persona": "Budget-conscious family shopper. Always hunts for deals and practical everyday value.",
        "preferences": ["grocery", "home"],
        "budget": 300.0,
    },
    {
        "agent_id": "consumer_emma",
        "name": "Emma Davis",
        "persona": "Impulsive aesthetic buyer. Drawn to visually appealing, Instagram-worthy products.",
        "preferences": ["fashion", "home", "electronics"],
        "budget": 1000.0,
    },
    {
        "agent_id": "consumer_tom",
        "name": "Tom Wilson",
        "persona": "Hardcore gamer and software developer. Has specific performance requirements and high standards.",
        "preferences": ["gaming", "electronics"],
        "budget": 1500.0,
    },
]
